ktor:
    application:
        modules:
            - org.mpo.app.ApplicationKt.module
    deployment:
        port: 8080
weather:
    apiKey: ${OWM_API_KEY:default_key_here}
    apiUrl: ${OWM_API_URL:https://api.openweathermap.org/data/2.5/forecast}